export enum EmailStatus {
  MAIL_PARSE_EXCEPTION = 'MAIL_PARSE_EXCEPTION',
  MAIL_AUTHENTICATION_EXCEPTION = 'MAIL_AUTHENTICATION_EXCEPTION',
  MAIL_SEND_EXCEPTION = 'MAIL_SEND_EXCEPTION',
  MAIL_EXCEPTION = 'MAIL_EXCEPTION',
  SUCCESS = 'SUCCESS',
}
